name: 'Smoke test'
inputs:
  template:
    description: 'Template to test'
    required: true

runs:
  using: composite
  steps:
    - name: Checkout main
      id: checkout_release
      uses: actions/checkout@v3

    - name: Build template
      id: build_template
      shell: bash
      run: .github/actions/smoke-test/build.sh ${{ inputs.template }}

    - name: Test template
      id: test_template
      shell: bash
      run: .github/actions/smoke-test/test.sh  ${{ inputs.template }}
