name: "CI - Test Templates"
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        templates: [rstudio, vscode]
    steps:
      - uses: actions/checkout@v4
      - name: "Copy startup scripts"
        run: |
          cp test/vm-metadata.sh startupscript/gcp/
          for dir in src/*/; do
            if [ -d "$dir" ]; then
              cp -r startupscript "$dir"
          fi
        done

      - name: Smoke test for '${{ matrix.templates }}'
        id: smoke_test
        uses: ./.github/actions/smoke-test
        with:
          template: "${{ matrix.templates }}"
